### PR TITLE
Updates for Idris style and documentation

### PR DESCRIPTION
**Pull request by david-christiansen**
Sorry! Wrong repo!

### CODE REVIEW

**Comment by sinelaw** [comment]
That's cool, now I know that idris is getting a wl-pprint package. Did you
consider basing it off one of the more recent packages, such as
https://hackage.haskell.org/package/ansi-wl-pprint ?

**Comment by david-christiansen** [comment]
I didn't do the initial port. However, once I get the types worked out, I'm going to graft on the features from `annotated-wl-pprint`, which I think gives a nicer interface for the kinds of things I like to do.

Cheers!

**Comment by mitchellwrosen** [comment]
@sinelaw 

Hi, I'm commenting here because I can't find any other place to do it :)

If this repo has replaced alexlegg/wl-pprint, could you please enable issues? (Go to Settings and check a box). This will allow people to file issues here rather than at the (defunkt?) original repository.

**Comment by sinelaw** [comment]
@mitchellwrosen yeah, done.

**Pull request closed without merging**
